name: sync-user-secrets
author: Jacob Hummer <jcbhmr@outlook.com> (https://jcbhmr.me/)
description: 🔒 Sync one repo's secrets to more repos
branding:
  icon: unlock
  color: yellow
inputs:
  token:
    required: true
  github-server-url:
    required: true
    default: ${{ github.server_url }}
  dry-run:
    required: true
    default: false
  query:
    required: true
  secrets:
    required: true
  secret-filter:
    required: true
    default: ""
runs:
  using: composite
  steps:
    - run: "./denow run -Aq cli.ts"
      shell: bash
      env:
        INPUT_TOKEN: ${{ inputs.token }}
        INPUT_GITHUB_SERVER_URL: ${{ inputs.github-server-url }}
        INPUT_DRY_RUN: ${{ inputs.dry-run }}
        INPUT_QUERY: ${{ inputs.query }}
        INPUT_SECRETS: ${{ inputs.secrets }}
        INPUT_SECRET_FILTER: ${{ inputs.secret-filter }}
