name: sync-user-secrets
author: Jacob Hummer <jcbhmr@outlook.com> (https://jcbhmr.me/)
description: 🔒 Sync one repo's secrets to more repos
branding:
  icon: unlock
  color: yellow
inputs:
  token:
    required: true
  github-server-url:
    required: true
    default: ${{ github.server_url }}
  dry-run:
    required: true
    default: false
  repository: {}
  repositories: {}
  query: {}
  app:
    required: true
    default: actions
  secret: {}
  secrets: {}
runs:
  using: composite
  steps:
    # prettier-ignore
    - run: '"${GITHUB_ACTION_PATH%/}/denow" run -Aq "${GITHUB_ACTION_PATH%/}/cli.ts"'
      shell: bash
      env:
        INPUT_TOKEN: ${{ inputs.token }}
        INPUT_GITHUB-SERVER-URL: ${{ inputs.github-server-url }}
        INPUT_DRY-RUN: ${{ inputs.dry-run }}
        INPUT_REPOSITORY: ${{ inputs.repository }}
        INPUT_REPOSITORIES: ${{ inputs.repositories }}
        INPUT_QUERY: ${{ inputs.query }}
        INPUT_SECRET: ${{ inputs.secret }}
        INPUT_SECRETS: ${{ inputs.secrets }}
