name: sync-user-secrets
author: Jacob Hummer <jcbhmr@outlook.com> (https://jcbhmr.me/)
description: 🔒 Sync one repo's secrets to more repos
branding:
  icon: unlock
  color: yellow
inputs:
  token:
    required: true
  github-server-url:
    required: true
    default: ${{ github.server_url }}
  dry-run:
    required: true
    default: false
  query:
    required: true
  secrets:
    required: true
  secret-filter:
    required: true
    default: ""
runs:
  using: composite
  steps:
    - run: '"${GITHUB_ACTION_PATH%/}/denow" run -Aq cli.ts'
      shell: bash
      env:
        INPUT: ${{ toJSON(inputs) }}
