#!/bin/sh
set -e
# https://betterdev.blog/minimal-safe-bash-script-template/
script_dir=$(cd "$(dirname "${BASH_SOURCE[0]}")" &>/dev/null && pwd -P)

# https://manpages.ubuntu.com/manpages/kinetic/en/man1/chronic.1.html
chronic() (
  set +e
  output=$($@ 2>&1)
  exit_code=$?
  set -e
  if [ "$exit_code" -ne 0 ]; then
    echo "$output" >&2
  fi
  return "$exit_code"
)

if [ ! -d .deno ]; then
    # https://github.com/denoland/deno_install#readme
    export DENO_INSTALL=.deno
    curl -fsSL https://deno.land/x/install/install.sh | chronic sh -s "v1.33.4"
fi

# https://github.com/denoland/deno_install/blob/master/install.sh#L53
export DENO_INSTALL=.deno
export PATH="$DENO_INSTALL/bin:$PATH"

exec "$script_dir/cli.ts" "$@"
