name: Test
on:
  push:
    branches: [main]
    paths:
      - "*.ts"
      - denow
      - denow.bat
      - action.yml
      - .github/workflows/test.yml
  pull_request:
    branches: [main]
    paths:
      - "*.ts"
      - denow
      - denow.bat
      - action.yml
      - .github/workflows/test.yml
concurrency:
  group: test-${{ github.ref }}
  cancel-in-progress: true
permissions:
  contents: write
jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: ./
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          secrets: '{ "TEST": "test" }'
          dry-run: true
      - name: ./:filter
        uses: ./
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          secrets: '{ "TEST": "test" }'
          filter: /sync-user-secrets$
          dry-run: true
